<h1>DATA SELECTION AND FILTERING</h1>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data-files/co2_emissions.csv")
print(df.head())

   year  month  decimal_date  co2_ppm     data_source    measurement_type
0  1958      3     1958.2027   315.71  NOAA_Mauna_Loa  atmospheric_direct
1  1958      4     1958.2877   317.45  NOAA_Mauna_Loa  atmospheric_direct
2  1958      5     1958.3699   317.51  NOAA_Mauna_Loa  atmospheric_direct
3  1958      6     1958.4548   317.27  NOAA_Mauna_Loa  atmospheric_direct
4  1958      7     1958.5370   315.87  NOAA_Mauna_Loa  atmospheric_direct

**<h4>ACCESS</h4>**

In [3]:
df["year"]

0     1958
1     1958
2     1958
3     1958
4     1958
      ...
95    1966
96    1966
97    1966
98    1966
99    1966
Name: year, Length: 100, dtype: int64

In [4]:
df[["year" , "month"]]

    year  month
0   1958      3
1   1958      4
2   1958      5
3   1958      6
4   1958      7
..   ...    ...
95  1966      2
96  1966      3
97  1966      4
98  1966      5
99  1966      6

[100 rows x 2 columns]

In [5]:
df.loc[0:1,"year"] #inclusive or lets slicing have em all

0    1958
1    1958
Name: year, dtype: int64

In [6]:
df.iloc[0:4, 0:3] #exclusive or doesn't allow that same in its slicing

   year  month  decimal_date
0  1958      3     1958.2027
1  1958      4     1958.2877
2  1958      5     1958.3699
3  1958      6     1958.4548

In [7]:
df.loc[1,["year","month"]]

year     1958
month       4
Name: 1, dtype: object

In [8]:
print(df.at[0,"year"]) #at and iat allow faster access but no slicing

1958

<h4>CONDITIONAL FILTERING</h4>

In [9]:
df[df["year"]>1960]

    year  month  decimal_date  co2_ppm     data_source    measurement_type
34  1961      1     1961.0411   316.89  NOAA_Mauna_Loa  atmospheric_direct
35  1961      2     1961.1260   317.70  NOAA_Mauna_Loa  atmospheric_direct
36  1961      3     1961.2027   318.54  NOAA_Mauna_Loa  atmospheric_direct
37  1961      4     1961.2877   319.48  NOAA_Mauna_Loa  atmospheric_direct
38  1961      5     1961.3699   320.58  NOAA_Mauna_Loa  atmospheric_direct
..   ...    ...           ...      ...             ...                 ...
95  1966      2     1966.1260   321.60  NOAA_Mauna_Loa  atmospheric_direct
96  1966      3     1966.2027   322.39  NOAA_Mauna_Loa  atmospheric_direct
97  1966      4     1966.2877   323.70  NOAA_Mauna_Loa  atmospheric_direct
98  1966      5     1966.3699   324.08  NOAA_Mauna_Loa  atmospheric_direct
99  1966      6     1966.4548   323.75  NOAA_Mauna_Loa  atmospheric_direct

[66 rows x 6 columns]

<h4>Syntax</h4>

(condition) & (condition)      # for AND  
(condition) | (condition)      # for OR  

For multiple conditions:
---

df[(condition) & (condition)][select]

df[condition].operation()

<h3>Query</h3><br>
so we can use the .query("query python like conditional syntax") <br>
--- <br>
for column name with spaces use `hello column`

In [15]:
#use .copy() method to get the copy as pandas may or may not return a copy without it
df2 = df.query("year == 1958 and co2_ppm > 313.5").copy()
df2

   year  month  decimal_date  co2_ppm     data_source    measurement_type
0  1958      3     1958.2027   315.71  NOAA_Mauna_Loa  atmospheric_direct
1  1958      4     1958.2877   317.45  NOAA_Mauna_Loa  atmospheric_direct
2  1958      5     1958.3699   317.51  NOAA_Mauna_Loa  atmospheric_direct
3  1958      6     1958.4548   317.27  NOAA_Mauna_Loa  atmospheric_direct
4  1958      7     1958.5370   315.87  NOAA_Mauna_Loa  atmospheric_direct
5  1958      8     1958.6219   314.93  NOAA_Mauna_Loa  atmospheric_direct
9  1958     12     1958.9562   314.67  NOAA_Mauna_Loa  atmospheric_direct