<h1>DATA FRAMES</h1>

In [12]:
import pandas as pd
import random

In [13]:
data = "abcdefghijklmnopqrstuvwxyz"

In [14]:
data[random.randrange(0,26)]

't'

In [15]:
df = [[f" {data[random.randrange(0,26)]} {data[random.randrange(0,26)]} {data[random.randrange(0,26)]}", i ] for i in range(100, 10000 , 100) ]

In [16]:
df2 = pd.DataFrame(df , columns = ["something's","fishy"])

In [17]:
df2

   something's  fishy
0        t s o    100
1        v i y    200
2        o v p    300
3        o r c    400
4        m u n    500
..         ...    ...
94       p p l   9500
95       u q o   9600
96       y a f   9700
97       g p o   9800
98       a e j   9900

[99 rows x 2 columns]

In [18]:
df2.head()

  something's  fishy
0       t s o    100
1       v i y    200
2       o v p    300
3       o r c    400
4       m u n    500

In [19]:
df2.tail()

   something's  fishy
94       p p l   9500
95       u q o   9600
96       y a f   9700
97       g p o   9800
98       a e j   9900

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   something's  99 non-null     object
 1   fishy        99 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.7+ KB

In [21]:
df2.describe()

             fishy
count    99.000000
mean   5000.000000
std    2872.281323
min     100.000000
25%    2550.000000
50%    5000.000000
75%    7450.000000
max    9900.000000

In [22]:
print(f"{df2.shape} is shape , the next one is columns {df2.columns}")

(99, 2) is shape , the next one is columns Index(['something's', 'fishy'], dtype='object')