<h1>DATA FRAMES</h1>

In [2]:
import pandas as pd
import random
import numpy as np

In [3]:
data = "abcdefghijklmnopqrstuvwxyz"

In [4]:
data[random.randrange(0,26)]

'h'

In [5]:
df = [[f" {data[random.randrange(0,26)]} {data[random.randrange(0,26)]} {data[random.randrange(0,26)]}", i ] for i in range(100, 10000 , 100) ]

In [6]:
df2 = pd.DataFrame(df , columns = ["something's","fishy"])

In [7]:
df2

   something's  fishy
0        d p t    100
1        f c g    200
2        k l e    300
3        s n m    400
4        h z w    500
..         ...    ...
94       l g u   9500
95       z q e   9600
96       t d m   9700
97       f g e   9800
98       p n w   9900

[99 rows x 2 columns]

In [8]:
df2.head()

  something's  fishy
0       d p t    100
1       f c g    200
2       k l e    300
3       s n m    400
4       h z w    500

In [9]:
df2.tail()

   something's  fishy
94       l g u   9500
95       z q e   9600
96       t d m   9700
97       f g e   9800
98       p n w   9900

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   something's  99 non-null     object
 1   fishy        99 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.7+ KB

In [11]:
df2.describe()

             fishy
count    99.000000
mean   5000.000000
std    2872.281323
min     100.000000
25%    2550.000000
50%    5000.000000
75%    7450.000000
max    9900.000000

In [12]:
print(f"{df2.shape} is shape , the next one is columns {df2.columns}")

(99, 2) is shape , the next one is columns Index(['something's', 'fishy'], dtype='object')

In [13]:
a = np.array([[1,2],[2,1]])
adf = pd.DataFrame(a,columns=["A","B"])
adf

   A  B
0  1  2
1  2  1