In [1]:
import pandas as pd

In [2]:
data  = pd.read_csv("../data-files/co2_emissions.csv")

In [3]:
data

    year  month  decimal_date  co2_ppm     data_source    measurement_type
0   1958      3     1958.2027   315.71  NOAA_Mauna_Loa  atmospheric_direct
1   1958      4     1958.2877   317.45  NOAA_Mauna_Loa  atmospheric_direct
2   1958      5     1958.3699   317.51  NOAA_Mauna_Loa  atmospheric_direct
3   1958      6     1958.4548   317.27  NOAA_Mauna_Loa  atmospheric_direct
4   1958      7     1958.5370   315.87  NOAA_Mauna_Loa  atmospheric_direct
..   ...    ...           ...      ...             ...                 ...
95  1966      2     1966.1260   321.60  NOAA_Mauna_Loa  atmospheric_direct
96  1966      3     1966.2027   322.39  NOAA_Mauna_Loa  atmospheric_direct
97  1966      4     1966.2877   323.70  NOAA_Mauna_Loa  atmospheric_direct
98  1966      5     1966.3699   324.08  NOAA_Mauna_Loa  atmospheric_direct
99  1966      6     1966.4548   323.75  NOAA_Mauna_Loa  atmospheric_direct

[100 rows x 6 columns]

In [4]:
data = data.sort_values(["co2_ppm"]).copy()

In [5]:
data

    year  month  decimal_date  co2_ppm     data_source    measurement_type
7   1958     10     1958.7890   312.42  NOAA_Mauna_Loa  atmospheric_direct
6   1958      9     1958.7068   313.21  NOAA_Mauna_Loa  atmospheric_direct
8   1958     11     1958.8740   313.33  NOAA_Mauna_Loa  atmospheric_direct
19  1959     10     1959.7890   313.33  NOAA_Mauna_Loa  atmospheric_direct
31  1960     10     1960.7896   313.83  NOAA_Mauna_Loa  atmospheric_direct
..   ...    ...           ...      ...             ...                 ...
74  1964      5     1964.3716   322.25  NOAA_Mauna_Loa  atmospheric_direct
96  1966      3     1966.2027   322.39  NOAA_Mauna_Loa  atmospheric_direct
97  1966      4     1966.2877   323.70  NOAA_Mauna_Loa  atmospheric_direct
99  1966      6     1966.4548   323.75  NOAA_Mauna_Loa  atmospheric_direct
98  1966      5     1966.3699   324.08  NOAA_Mauna_Loa  atmospheric_direct

[100 rows x 6 columns]

In [8]:
data.reset_index(drop=True,inplace=True)

In [9]:
data

    year  month  decimal_date  co2_ppm     data_source    measurement_type
0   1958     10     1958.7890   312.42  NOAA_Mauna_Loa  atmospheric_direct
1   1958      9     1958.7068   313.21  NOAA_Mauna_Loa  atmospheric_direct
2   1958     11     1958.8740   313.33  NOAA_Mauna_Loa  atmospheric_direct
3   1959     10     1959.7890   313.33  NOAA_Mauna_Loa  atmospheric_direct
4   1960     10     1960.7896   313.83  NOAA_Mauna_Loa  atmospheric_direct
..   ...    ...           ...      ...             ...                 ...
95  1964      5     1964.3716   322.25  NOAA_Mauna_Loa  atmospheric_direct
96  1966      3     1966.2027   322.39  NOAA_Mauna_Loa  atmospheric_direct
97  1966      4     1966.2877   323.70  NOAA_Mauna_Loa  atmospheric_direct
98  1966      6     1966.4548   323.75  NOAA_Mauna_Loa  atmospheric_direct
99  1966      5     1966.3699   324.08  NOAA_Mauna_Loa  atmospheric_direct

[100 rows x 6 columns]